export default [
  {
    username: "나보다많을까",
    nickname: "psky",
    position: ["mid", "adc"],
    tier: "P3",
    recent_win: 12,
    recent_defeat: 8,
    most: [],
    kda: 3.7,
    poro: 70,
    synergy: 65,
    total_win: 43,
    total_defeat: 19,
    profileIconId: 1,
    summonerLevel: 30,
  },
  {
    username: "SKT T1 Faker",
    nickname: "t1_faker",
    position: ["mid"],
    tier: "C1",
    recent_win: 19,
    recent_defeat: 1,
    most: [],
    kda: 17,
    poro: 92,
    synergy: 70,
    total_win: 100,
    total_defeat: 20,
    profileIconId: 1,
    summonerLevel: 30,
  },
  {
    username: "쵸비",
    nickname: "hle_chovy",
    position: ["mid", "sup"],
    tier: "C1",
    recent_win: 17,
    recent_defeat: 3,
    most: [],
    kda: 42,
    poro: 88,
    synergy: 80,
    total_win: 200,
    total_defeat: 57,
    profileIconId: 1,
    summonerLevel: 30,
  },
];
